name: 'build-test'
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - run: yarn package

      # Test built action itself
      - uses: ./dist/
        with:
          geckodriver-version: "0.26.0"
      - run: geckodriver --version
      - uses: ./dist/
      - run: geckodriver --version
  test-latest:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    needs: [build]
    steps:
      - uses: midnight-madman/setup-geckodriver@latest
        with:
          geckodriver-version: "0.26.0"
      - run: geckodriver --version
      - uses: midnight-madman/setup-geckodriver@latest
      - run: geckodriver --version

